#include "fixture_data.h"

const char *g_fixture_personal_usage_json = "{\n"
"  \"schema_version\": 1,\n"
"  \"source\": \"fixture\",\n"
"  \"captured_at\": \"2026-09-11T00:00:00Z\",\n"
"  \"account_scope\": \"synthetic-example\",\n"
"  \"windows\": [\n"
"    {\n"
"      \"id\": \"five-hour\",\n"
"      \"label\": \"5-hour window\",\n"
"      \"percent_used\": 42,\n"
"      \"percent_remaining\": 58,\n"
"      \"resets_at\": null\n"
"    },\n"
"    {\n"
"      \"id\": \"weekly\",\n"
"      \"label\": \"Weekly window\",\n"
"      \"percent_used\": 18,\n"
"      \"percent_remaining\": 82,\n"
"      \"resets_at\": null\n"
"    }\n"
"  ],\n"
"  \"stale\": false,\n"
"  \"error_code\": null,\n"
"  \"notes\": \"Synthetic values only. No account token, cookie, or personal usage export is included.\"\n"
"}\n";

const char *g_fixture_codex_reset_forecast_json = "{\n"
"  \"schema_version\": 1,\n"
"  \"source\": \"codex-reset.com\",\n"
"  \"captured_at\": \"2026-09-10T16:54:07Z\",\n"
"  \"last_reset_at\": \"2026-09-08T04:05:53Z\",\n"
"  \"forecast_24h_percent\": 22,\n"
"  \"forecast_48h_percent\": 39,\n"
"  \"forecast_is_schedule\": false,\n"
"  \"confidence\": \"low\",\n"
"  \"stale\": false,\n"
"  \"error_code\": null,\n"
"  \"source_url\": \"https://codex-reset.com/api/forecast\"\n"
"}\n";

const char *g_fixture_codex_resets_history_json = "{\n"
"  \"schema_version\": 1,\n"
"  \"source\": \"codex-resets.com\",\n"
"  \"captured_at\": \"2026-09-10T16:54:07Z\",\n"
"  \"latest_reset_at\": \"2026-09-08T01:56:00Z\",\n"
"  \"stale\": false,\n"
"  \"error_code\": null,\n"
"  \"source_url\": \"https://codex-resets.com/\"\n"
"}\n";
